version: '3'
services:
  davinci-ui:
    labels:
      - "maintainer=caozhiwu@wctsoft.com"
    image: registry.cn-shenzhen.aliyuncs.com/wct/davinci-ui:latest
    restart: always
    build:
      context: .
      args:
        REACT_APP_HOST_IP: $REACT_APP_HOST_IP
    ports:
      - ${PORT:-9030}:80
